### ISSUE TITLE
Improving UX regarding code blocks actions (vs. reference or snippets)

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#15]
For the docs, one note I had yesterday is that it often is unclear when code is referenced whether the reader should take action or just examine. Maybe potential improvements in the future could be:
- if a whole file is given, assume it’s Copy+Replace file
- if a snippet is given, a yellow highlight indicates a change you need to replace in the file --> so take action (note: I’m thinking the yellow highlight example TPW sent us)
- if a snippet is given without yellow highlight. There’s no action. It’s just for reference.

**Comment by jrhorn424** [comment]
Was thinking the same when working through the tutorial. It's a high quality tutorial as-is! I had a few different thoughts about improving the learner experience. How about:

* if a block is copyable, the copy controls appear
* if a block is not copyable, the copy controls do not appear
* if a block has a highlight, the copy controls appear, but the copy function only copies highlighted lines.

**Comment by cannikin** [comment]
Found this package: https://www.npmjs.com/package/markdown-it-highlight-lines

Will require that we convert from [marked](https://github.com/markedjs/marked) to [markdown-it](https://github.com/markdown-it/markdown-it) but might not be too bad!

I'm not exactly loving having to count down line numbers, but otherwise we have to invent some kind of custom markdown parser (or write our own plugin for something like markdown-it).

**Comment by cannikin** [comment]
Finally done!
