### ISSUE TITLE
Search finds missing cells docs page

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwoodjs.com#228]
![image](https://user-images.githubusercontent.com/30793/86480588-96017c80-bd4e-11ea-82cc-8d522a0b141d.png)

Clicking on that first link for the Cells docs, I get this

![image](https://user-images.githubusercontent.com/30793/86480645-b16c8780-bd4e-11ea-9be6-459cc8ef15ee.png)

**Comment by Tobbe** [comment]
Is algolia picking up on this? https://github.com/redwoodjs/redwoodjs.com/pull/202

**Comment by cannikin** [comment]
Hmm...PRs and branches are supposed to use a separate algolia index now, the production one should only be what's in `main` now. I'll double check that it's working as expected...

**Comment by cannikin** [comment]
Okay I double checked and this is working correctly when Netlify is deploying—`main` builds populate the `docs` index on Algolia and branch and PR builds populate the `docs-branch` index. I cleared out the `docs` index and re-deployed `main`, then re-deployed the WIP cells PR and `docs` didn't change at all, as expected.

The only thing I can this of is that someone is writing to the `docs` index in their local development environment, but I don't think I gave anyone else the Algolia API key, so that shouldn't be possible. I double checked my local `.env` and `.env.defaults` and I'm using the correct `docs-dev` index.

**Comment by jtoar** [comment]
@cannikin I‘ll check to make sure I’m not doing this somehow.

> The only thing I can this of is that someone is writing to the docs index in their local development environment, but I don't think I gave anyone else the Algolia API key, so that shouldn't be possible.

**Comment by cannikin** [comment]
I'll also rotate the API key just in case!

**Comment by dthyresson** [comment]
Performed the search for "beforeQuery" and was able to select the "Cells" page and view.

Looks to be fixed.

**Comment by Tobbe** [comment]
> Performed the search for "beforeQuery" and was able to select the "Cells" page and view.
> 
> Looks to be fixed.

Yeah, it doesn't seem to be finding that PR branch anymore 👍
