### ISSUE TITLE
Create a Quick Start doc

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#339]
Continues conversation from https://github.com/redwoodjs/redwood/pull/1060#issuecomment-686835122

- Remove content from https://redwoodjs.com/docs/introduction#quickstart
- ...and create a new Quick Start doc that would go directly below "Introduction" in left Nav
- Add link in main README.md to the new Quick Start doc within the same callout as the **Tutorial** at the top of the page

We should consider a bit more content for the Quick Start such as DB commands and getting started with CLI (e.g. --help to see all commands and one example of a generator). Also hard to not give some overview about basic structure like GraphQL, React, Prisma and API Side and Web side.

**Comment by kevPo** [comment]
@thedavidprice 

I submitted a [PR](https://github.com/redwoodjs/redwoodjs.com/pull/414) for the new Quick Start doc. I'm working on another PR to update the main README.md now and I was curious if you had a preference for what the copy should be for the Quick Start callout? 

This is what I came up with, but I wanted to make sure to match the tone and language that you all would prefer. Any suggestions?

> **QUICK START:** It might be hard to believe, but a full-stack application can be
> running on your machine with only two commands. Check out the [Quick Start Guide](https://redwoodjs.com/docs/quick-start)
> to see for yourself.

**Comment by ajcwebdev** [comment]
Not David, but I have some thoughts on this and thought I'd share my 2 cents. This is completely my personal opinion and the core team may disagree, but one of the things that I really dislike about a lot of modern open source projects' docs is that I constantly feel like they are trying to sell me the framework.

I understand why this is a trend and from a strategic standpoint it might be the right thing to do, but I always feel gross reading docs like that. Which is to say, your copy is great, too good actually! Because it reads like you're trying to sell the start up guide it feels off to me.

I don't know if this was on purpose or not, but one of the things that I really love about the Redwood docs is that they will occasionally do this but always in a [self-conscious tongue in cheek way](https://en.wikipedia.org/wiki/Lampshade) (I think this is also why the infomercial is so hilarious). Here's a few examples of what I mean by that:

> Redwood had figured out a way to make forms less soul-sucking than usual. In fact Redwood might even make you love building forms. Well, love is a strong word. Like building forms. Tolerate building them?

> How can it be serverless if it involves a GraphQL API and database? I'm glad you asked!

So I guess my specific suggestion would be, to try to add a little more personality. I'm trying to think of a joke to put after the two commands comment, but I'm coming up blank right now.

**Comment by thedavidprice** [comment]
Thanks for getting this going, @kevPo 🚀

### Redwoodjs.com Doc https://github.com/redwoodjs/redwoodjs.com/pull/414
I added a lot of notes and suggestions in an attempt to start with a bit more of a foundation. But definitely not intended to overwhelm. Take the pieces that feel easily actionable to you and run with them. For the pieces (or new + other ideas), could you create a new Issue, something like "Improving Quick Start", and add the items there for the next steps.

### Copy for Quick Start Callout 
I understand where @ajcwebdev is coming from. As a standalone copy, this _can_ read that way. But inline with the rest of the doc I don't think the tone will be the same. That said, I'll defer to you. Here's my suggestion either way:

>QUICK START: You can install and run a full-stack Redwood application on your machine with only two commands. Check out the Quick Start Guide to get started.

---

Keep me posted!
