### ISSUE TITLE
Conflicting instructions regarding m-n relationships in schema.prisma

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/redwoodjs.com#595]
Hello!

I'm working with a freshly generated Redwood project, using `"@redwoodjs/core": "^0.25.1"`. I've only setup a `prisma.schema` and am generating scaffolding to go along with it. I'm using y'alls [documentation on doing relations with the Redwood generator](https://redwoodjs.com/docs/schema-relations#prisma-relations-and-redwoods-generators) and comparing that to [Prisma's docs](https://www.prisma.io/docs/concepts/components/prisma-schema/relations).

When I go about implementing [this](https://redwoodjs.com/docs/schema-relations#supported-table-structure) part of your documentation, I run into the following IDE error:

```Terminal
Error validating model "PalletProduct": Each model must have at most one id criteria. You can't have `@id` and `@@id` at the same time.
```

In my use-case I actually will benefit from defining the relating model, explicitly as Prisma refers to it. I just wanted to clear-up how I should go about resolving this?

I'm assuming either my IDE's bugging-out or I need to remove `@@id` and `@@unique` constrain my referencing columns. I can provide my schema if it'll help any, but it's pretty much a copy-pasta of the documentation.

**Comment by cannikin** [comment]
Yeah we've updated docs with info about this: https://redwoodjs.com/docs/schema-relations

Unfortunately if you want to scaffold a many-to-many join table you need an `@id` column, but as far as Prisma is concerned you're not allowed to have that and the `@@id` declaration at the same time.

This is because all of Redwood's scaffolding logic depends on having an `id` to look up, edit and delete a record. We don't have an easy way to uniquely identify a record any other way. It's possible we could inspect your model and find the indexes (created by `@@id`) and somehow use those to lookup a single, unique record, but it's not currently in the roadmap.

**Comment by realStandal** [comment]
Updating my schema to use `@@unique` instead of `@@id` worked and surpressed `rw g scaffold`-s error. My schema now looks like:

```Prisma
// ...other models

model PalletProduct {
  @@map(name: "pallet_products")

  id              String      @id @default(uuid())
  pallet          Pallet      @relation(fields: [palletId], references: [id])
  palletId        String
  product         Product     @relation(fields: [productId], references: [id])
  productId       String
  updatedAt       DateTime    @updatedAt
  createdAt       DateTime    @default(now())

  @@unique([palletId, productId])
}
```

**Comment by realStandal** [comment]
I hit Comment after you'd posted, sorry.

I'm talking about how [this example](https://redwoodjs.com/docs/schema-relations#supported-table-structure) on the docs recommends having both `@id` and `@@id` defined. I'd assume it wouldn't pan out, I don't think it's a big issue `@@unqiue` accomplishes the same thing and makes sure one pallet only ever has one instance of a particular product.

**Comment by cannikin** [comment]
Ahhh, interesting! I don't think we'd actually tested doing both `@id` and `@@id`... I thought `@@id` was just an index so it wouldn't matter, but maybe it actually tries to impose a primary key on those fields, and since there can only be one primary key...

I'll update the docs to talk about `@@unique` instead of `@@id`!

**Comment by realStandal** [comment]
Thank you for helping to clear it up! I can make the change and submit a PR if you'd like, think that's within my skill-scope lol

**Comment by cannikin** [comment]
That would be great, thank you! I'll assign this to you instead! :)
